In [1]:
import numpy as np

In [2]:
np.array??

In [3]:
a = np.array

In [4]:
a

<function numpy.array>

In [5]:
a = np.array(1)

In [6]:
a

array(1)

In [7]:
a = np.array([1,])

In [8]:
a

array([1])

In [9]:
a = np.array((1,))

In [10]:
a

array([1])

-> mutable이다. 데이터를 변경했을 때 side effect가 생긴다. 데이터 손실에 유의

copy method를 잘 알아야 한다.

In [11]:
a = np.array([[1,2],[3,4]])

In [12]:
a

array([[1, 2],
       [3, 4]])

In [13]:
n = np.ndarray(0)

In [14]:
n

array([], dtype=float64)

객체를 이용해서 인스턴스화 해서 사용하기

In [15]:
a = np.array([1,2,3])

In [16]:
a

array([1, 2, 3])

In [17]:
a = np.array(['1',2,3])

In [18]:
a

array(['1', '2', '3'], dtype='<U1')

In [19]:
n = np.ndarray([0,'1'])

TypeError: 'str' object cannot be interpreted as an integer

In [20]:
a = np.array([[1,2],[3,4]])

In [21]:
a

array([[1, 2],
       [3, 4]])

In [22]:
a.ndim

2

In [23]:
len(a)

2

In [24]:
a.shape

(2, 2)

In [25]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

 C_CONTIGUOUS : True

-> 저장 방식을 보여준다.

 C_CONTIGUOUS : C 방식의 저장 왼->오 저장(1234)
 
 F_CONTIGUOUS : Fortran반식 위-아래 저장(1324)
 
 

In [26]:
a.size

4

In [27]:
a.itemsize

4

In [28]:
a.dtype

dtype('int32')

In [29]:
b = np.array([[1,2],[3,4]])

In [30]:
b

array([[1, 2],
       [3, 4]])

In [32]:
x = [1,2,3,4]
y = [2,3,4,5]

In [33]:
x + y

[1, 2, 3, 4, 2, 3, 4, 5]

In [34]:
a+b

array([[2, 4],
       [6, 8]])

numpy array 구조는 각각의 원소끼리 연산한다.

In [35]:
[(a+b) for a,b in zip(x,y)]

[3, 5, 7, 9]

In [36]:
a - b

array([[0, 0],
       [0, 0]])

In [37]:
a*b

array([[ 1,  4],
       [ 9, 16]])

In [39]:
a.T??

In [40]:
a.strides

(8, 4)

## ** Stride

실제 내부 구조는 한줄. Stride를 이용해 배열을 나누어 준다.

---

## dtype

In [41]:
a = np.array([[1,2],[3,4]],dtype='i8')

In [42]:
a

array([[1, 2],
       [3, 4]], dtype=int64)

In [43]:
a = np.array([[1,2],[3,4]],dtype='u1')

In [44]:
a

array([[1, 2],
       [3, 4]], dtype=uint8)

In [45]:
np.sctypeDict

{'?': numpy.bool_,
 0: numpy.bool_,
 'byte': numpy.int8,
 'b': numpy.int8,
 1: numpy.int8,
 'ubyte': numpy.uint8,
 'B': numpy.uint8,
 2: numpy.uint8,
 'short': numpy.int16,
 'h': numpy.int16,
 3: numpy.int16,
 'ushort': numpy.uint16,
 'H': numpy.uint16,
 4: numpy.uint16,
 'i': numpy.int32,
 5: numpy.int32,
 'uint': numpy.uint32,
 'I': numpy.uint32,
 6: numpy.uint32,
 'intp': numpy.int64,
 'p': numpy.int64,
 9: numpy.int64,
 'uintp': numpy.uint64,
 'P': numpy.uint64,
 10: numpy.uint64,
 'long': numpy.int32,
 'l': numpy.int32,
 7: numpy.int32,
 'L': numpy.uint32,
 8: numpy.uint32,
 'longlong': numpy.int64,
 'q': numpy.int64,
 'ulonglong': numpy.uint64,
 'Q': numpy.uint64,
 'half': numpy.float16,
 'e': numpy.float16,
 23: numpy.float16,
 'f': numpy.float32,
 11: numpy.float32,
 'double': numpy.float64,
 'd': numpy.float64,
 12: numpy.float64,
 'longdouble': numpy.float64,
 'g': numpy.float64,
 13: numpy.float64,
 'cfloat': numpy.complex128,
 'F': numpy.complex64,
 14: numpy.complex64,
 'c

In [46]:
len(np.sctypeDict)

152

In [47]:
np.show_config()

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/scminnoG15/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/scminnoG15/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/scminnoG15/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\m

In [48]:
np.sctypeDict.keys()

dict_keys(['?', 0, 'byte', 'b', 1, 'ubyte', 'B', 2, 'short', 'h', 3, 'ushort', 'H', 4, 'i', 5, 'uint', 'I', 6, 'intp', 'p', 9, 'uintp', 'P', 10, 'long', 'l', 7, 'L', 8, 'longlong', 'q', 'ulonglong', 'Q', 'half', 'e', 23, 'f', 11, 'double', 'd', 12, 'longdouble', 'g', 13, 'cfloat', 'F', 14, 'cdouble', 'D', 15, 'clongdouble', 'G', 16, 'O', 17, 'S', 18, 'unicode', 'U', 19, 'void', 'V', 20, 'M', 21, 'm', 22, 'bool8', 'Bool', 'b1', 'int64', 'Int64', 'i8', 'uint64', 'Uint64', 'u8', 'float16', 'Float16', 'f2', 'float32', 'Float32', 'f4', 'float64', 'Float64', 'f8', 'complex64', 'Complex32', 'c8', 'complex128', 'Complex64', 'c16', 'object0', 'Object0', 'bytes0', 'Bytes0', 'str0', 'Str0', 'void0', 'Void0', 'datetime64', 'Datetime64', 'M8', 'timedelta64', 'Timedelta64', 'm8', 'int32', 'Int32', 'i4', 'uint32', 'UInt32', 'u4', 'UInt64', 'int16', 'Int16', 'i2', 'uint16', 'UInt16', 'u2', 'int8', 'Int8', 'i1', 'uint8', 'UInt8', 'u1', 'complex_', 'int0', 'uint0', 'single', 'csingle', 'singlecomplex', 

In [49]:
a = np.arange(10)

In [50]:
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [51]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

-> reshape function은 input array에 변경된 데이터를 적용하지 않고 반환값만 보여준다.

In [52]:
a = a.reshape(2,5)

변경을 원한다면 재할당을 해줘여한다.

In [53]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [54]:
a.sum(axis=0)

array([ 5,  7,  9, 11, 13])

In [55]:
a.sum(axis=1)

array([10, 35])

In [56]:
a.sum()

45

In [57]:
a.mean()

4.5

## numpy 성능 췤

In [58]:
import time

In [59]:
%time sum(x for x in range(1000000))

Wall time: 101 ms


499999500000

In [60]:
%time np.sum(np.arange(1000000))

Wall time: 4 ms


1783293664

넘파이의 호모지니어스한 특징, C기반의 구현이 Python보다 연산에 최적화되어있다.

-> numpy를 이용해서 코딩을 하면 자동적으로 최적화가 된다.

In [61]:
a = np.zeros((3,4))

In [62]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [63]:
b = np.ones((3,4))

In [65]:
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [66]:
c = np.full((3,4),6)

In [67]:
c

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [68]:
np.zeros_like??

In [70]:
d = np.ones_like(a)

In [71]:
d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [72]:
d = np.ones_like(2)

In [73]:
d

array(1)

-> ~_like : shape를 맞춰준다.

## 단위 행렬
주대각선의 원소가 모두 1이며 나머지 원소는 모두 0인 정사각 행렬


In [74]:
np.eye??

In [75]:
e = np.eye(3)

In [76]:
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [77]:
np.identity??

In [78]:
np.diag??

## 상 삼각행렬 / 하 삼각행렬

정 사각행렬의 주대각선을 기준으로 대각항의 위쪽이나 아래쪽 항들의 값이 모두 0인 경우를 의미한다.

In [79]:
f = np.triu((3,3))

In [81]:
f

array([[3, 3],
       [0, 3]])

In [94]:
f = np.tri(3)

In [95]:
f

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

## 집규행렬 / 전치행렬

In [96]:
g = np.linspace(0,99)

In [97]:
g

array([ 0.        ,  2.02040816,  4.04081633,  6.06122449,  8.08163265,
       10.10204082, 12.12244898, 14.14285714, 16.16326531, 18.18367347,
       20.20408163, 22.2244898 , 24.24489796, 26.26530612, 28.28571429,
       30.30612245, 32.32653061, 34.34693878, 36.36734694, 38.3877551 ,
       40.40816327, 42.42857143, 44.44897959, 46.46938776, 48.48979592,
       50.51020408, 52.53061224, 54.55102041, 56.57142857, 58.59183673,
       60.6122449 , 62.63265306, 64.65306122, 66.67346939, 68.69387755,
       70.71428571, 72.73469388, 74.75510204, 76.7755102 , 78.79591837,
       80.81632653, 82.83673469, 84.85714286, 86.87755102, 88.89795918,
       90.91836735, 92.93877551, 94.95918367, 96.97959184, 99.        ])

In [98]:
h = np.logspace(1,100)

In [99]:
h

array([1.00000000e+001, 1.04811313e+003, 1.09854114e+005, 1.15139540e+007,
       1.20679264e+009, 1.26485522e+011, 1.32571137e+013, 1.38949549e+015,
       1.45634848e+017, 1.52641797e+019, 1.59985872e+021, 1.67683294e+023,
       1.75751062e+025, 1.84206997e+027, 1.93069773e+029, 2.02358965e+031,
       2.12095089e+033, 2.22299648e+035, 2.32995181e+037, 2.44205309e+039,
       2.55954792e+041, 2.68269580e+043, 2.81176870e+045, 2.94705170e+047,
       3.08884360e+049, 3.23745754e+051, 3.39322177e+053, 3.55648031e+055,
       3.72759372e+057, 3.90693994e+059, 4.09491506e+061, 4.29193426e+063,
       4.49843267e+065, 4.71486636e+067, 4.94171336e+069, 5.17947468e+071,
       5.42867544e+073, 5.68986603e+075, 5.96362332e+077, 6.25055193e+079,
       6.55128557e+081, 6.86648845e+083, 7.19685673e+085, 7.54312006e+087,
       7.90604321e+089, 8.28642773e+091, 8.68511374e+093, 9.10298178e+095,
       9.54095476e+097, 1.00000000e+100])

In [100]:
i = np.empty((4,2))

In [101]:
i

array([[0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 6.91691904e-321],
       [1.15706964e-306, 2.33419537e-312]])

-> empty C에서 들고온 기능. 쓰레기값을 채우는 기능

In [103]:
a = np.arange(10).reshape(2,5)

In [104]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

인덱싱 / keys

### numpy indexing은 확장되어있다.

In [105]:
# 기본적인 파이썬 방식
a[1][3]

8

In [106]:
# numpy 방식 python에서 지원하지 않는다.
a[1,3]

8

In [107]:
a[:,3]

array([3, 8])

-> 행에서 3번째꺼 axis = 1

array[2,:] : 행의 인덱스가 2인 값(3행) 을 추출

array[1:3,] : 행의 인덱스가 1,2인 값(2,3 행)을 추출

array[:,3] : 열의 인덱스가 3인 값(4열)을 추출

array[:,:2] : 열의 인덱스가 2미만읜 값(인덱스0,1 = 1,2열) 을 추출

array[3,2] : 행의 인덱스가 3, 열의 인덱스가 2(4행 3열)인 값을 추출

array[:2,1:3]=0 : 단일차원과 마찬가지로 해당 값에 0을 삽입

In [108]:
a = np.arange(27).reshape(3,3,3)

In [109]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [110]:
a[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [111]:
a[1,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [112]:
a[1,...]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [113]:
a[0,2:4]

array([[6, 7, 8]])

In [114]:
b = np.arange(36).reshape(6,6)

In [115]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [116]:
b[0,3:5]

array([3, 4])

In [117]:
b[4:,4:]

array([[28, 29],
       [34, 35]])

In [118]:
b[:,2]

array([ 2,  8, 14, 20, 26, 32])

In [119]:
b[2::2,::2]

array([[12, 14, 16],
       [24, 26, 28]])

In [120]:
a = np.arange(10)

In [121]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
a[a>3]

array([4, 5, 6, 7, 8, 9])

In [123]:
a[a>3 & a<8]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [124]:
a[(a>3)*(a<8)]

array([4, 5, 6, 7])

In [125]:
a[(a>3)|(a<8)]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

마스킹 기법

In [126]:
a[[True,False,True,True,True,True,True,True,True,True]]

array([0, 2, 3, 4, 5, 6, 7, 8, 9])

In [127]:
a>3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

## Fancy indexing

In [128]:
a[[1,2]]

array([1, 2])

In [129]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:
a = np.arange(15).reshape(5,3)

In [131]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [132]:
a[[1,2]]

array([[3, 4, 5],
       [6, 7, 8]])

In [133]:
a[[1,3]]

array([[ 3,  4,  5],
       [ 9, 10, 11]])

In [134]:
a[(0,1),(1,2)]

array([1, 5])

-> tuple은 원소 춧출

In [136]:
a[3:,[0,2]]

array([[ 9, 11],
       [12, 14]])

In [137]:
a = np.arange(25).reshape(5,5)

In [138]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [139]:
a[0]

array([0, 1, 2, 3, 4])

In [141]:
a[1,3:5]

array([8, 9])

In [142]:
a[:,4]

array([ 4,  9, 14, 19, 24])

In [143]:
a[-2:,-2:]

array([[18, 19],
       [23, 24]])

In [144]:
a[2::2,::2]

array([[10, 12, 14],
       [20, 22, 24]])

In [145]:
a[3:,[0,1,3]]

array([[15, 16, 18],
       [20, 21, 23]])

In [146]:
np.nditer??

In [147]:
b = np.nditer(a)

In [148]:
b

In [149]:
next(b)

array(0)

In [150]:
next(b)

array(1)

In [151]:
3+[1,2,3]

TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [152]:
3+np.arange(10)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

-> Broad Cast

In [153]:
[1, 2] + np.arange(10)

ValueError: operands could not be broadcast together with shapes (2,) (10,) 

간단한 구조가 아니면 broad cast 지원 해주지 않는다.

## Universal function
기본적으로 파이썬에서 지원하는 함수는 대부분 있다.

In [154]:
np.ufunc??

In [155]:
np.ceil??

In [156]:
np.info(np.ceil)

ceil(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Return the ceiling of the input, element-wise.

The ceil of the scalar `x` is the smallest integer `i`, such that
`i >= x`.  It is often denoted as :math:`\lceil x \rceil`.

Parameters
----------
x : array_like
    Input data.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
y : ndarray or scalar
    The ceilin

universal function은 np.info() 코드로 정보를 볼 수 있다.

np.info() : numpy 함수를 자세하게 볼 수 있는 메소드

scipy에서 더 고급 함수를 지원한다.

---

## where

In [157]:
b = np.arange(10)

In [158]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [159]:
np.where(b>5,0,1)

array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0])

In [160]:
b = np.arange(5,10)

In [161]:
b

array([5, 6, 7, 8, 9])

In [163]:
np.where(b>5)

(array([1, 2, 3, 4], dtype=int64),)

-> index값을 표시

In [162]:
# 값
np.max(b)

9

In [164]:
# index
np.argmax(b)

4

In [165]:
# index
np.argmin(b)
# 함수 방식

0

In [166]:
b.argmax()
# 메소드 방식

4

numpy는 보통 함수방식, 메소드 방식을 모두지원하는 경우가 많다.

-> 함수 - 메소드 방식을 다르게 지원하는 것들이 있다.

In [167]:
b.data