In [1]:
import numpy as np

In [2]:
import torch

In [15]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])

In [16]:
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [17]:
print("Rank of t : ", t.ndim)

Rank of t :  1


In [18]:
print("Shape of t : ", t.shape)

Shape of t :  (7,)


In [22]:
print("t[0] t[1] t[-1] = ", t[0], t[1], t[-1])
# Element

t[0] t[1] t[-1] =  0.0 1.0 6.0


In [20]:
print("t[2:5] t[4:-1] = ", t[2:5], t[4:-1])
# Slicing

t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]


In [21]:
print("t[:2] t[3:] = ", t[:2], t[3:])
# Slicing

t[:2] t[3:] =  [0. 1.] [3. 4. 5. 6.]


### 2D Array with Numpy

In [23]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])

In [24]:
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [25]:
print("Rank of t : ", t.ndim)

Rank of t :  2


In [26]:
print("Shape of t : ", t.shape)

Shape of t :  (4, 3)


### PyTorch Tensor

In [27]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])

In [28]:
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [30]:
print(t.dim()) #rank

1


In [31]:
print(t.shape) 

torch.Size([7])


In [32]:
print(t.size()) # shape

torch.Size([7])


In [33]:
print(t[0], t[1], t[-1]) # Element

tensor(0.) tensor(1.) tensor(6.)


In [34]:
print(t[2:5], t[4:-1])

tensor([2., 3., 4.]) tensor([4., 5.])


In [35]:
print(t[:2], t[3:])

tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [36]:
t = torch.FloatTensor([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])

In [37]:
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [38]:
print(t.dim())

2


In [39]:
print(t.size())

torch.Size([4, 3])


In [41]:
print(t[:, 1])

tensor([ 2.,  5.,  8., 11.])


In [43]:
print(t[:, 1].size())

torch.Size([4])


In [44]:
print(t[:, -1])

tensor([ 3.,  6.,  9., 12.])


### Broadcasting

pytorch는 행렬 연산에서 사이즈가 같지 않은 행렬의 연산을 도와준다.

In [3]:
# same shape
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])

In [4]:
print(m1 + m2)

tensor([[5., 5.]])


In [6]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3])

In [7]:
print(m1 + m2)

tensor([[4., 5.]])


In [8]:
# m2 = torch.FloatTensor([3]) : 3 -> [[3, 3]]
# pytorch가 자동으로 scalar를 텐서로 바꿔준다.

In [9]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3],[4]])

In [10]:
print(m1+m2)

tensor([[4., 5.],
        [5., 6.]])


In [11]:
# -> [[1,2],[1,2]] + [[3, 3],[4,4]]

### Multilication vs Matirix Multiplication

[[1,2],[3,4]] x [[1,1],[2,2]] = [[1,2],[6,8]]

### Mean

In [12]:
t = torch.FloatTensor([1,2])

In [13]:
print(t.mean())

tensor(1.5000)


In [14]:
# Can't use mean() on integers
t = torch.LongTensor([1, 2])

In [15]:
try :
    print(t.mean())
except Exception as e:
    print(e)

Can only calculate the mean of floating types. Got Long instead.


In [16]:
t = torch.FloatTensor([[1,2],[3,4]])

In [17]:
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [18]:
print(t.mean())

tensor(2.5000)


In [19]:
print(t.mean(dim=0))
# 2x2 -> 1x2
# ->

tensor([2., 3.])


In [20]:
print(t.mean(dim=1))
# 2x2 -> 2x1
# 위 아래

tensor([1.5000, 3.5000])


In [21]:
print(t.mean(dim=-1))

tensor([1.5000, 3.5000])


### SUM

In [22]:
t = torch.FloatTensor([[1,2],[3,4]])

In [23]:
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [24]:
print(t.sum())

tensor(10.)


In [25]:
print(t.sum(dim=0))

tensor([4., 6.])


In [26]:
print(t.sum(dim=0))

tensor([4., 6.])


In [28]:
print(t.sum(dim=1))

tensor([3., 7.])


In [29]:
print(t.sum(dim=-1))

tensor([3., 7.])


### Max and Argmax

In [30]:
t = torch.FloatTensor([[1,2],[3,4]])

In [31]:
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [32]:
print(t.max())

tensor(4.)


In [33]:
print(t.max(dim=0))

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [34]:
print("Max : ", t.max(dim=0)[0])

Max :  tensor([3., 4.])


In [35]:
print("Argmax : ", t.max(dim=0)[1])

Argmax :  tensor([1, 1])


In [36]:
print(t.max(dim=1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


In [37]:
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
