In [3]:
import numpy as np

In [14]:
import torch

In [15]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])

In [16]:
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [17]:
print("Rank of t : ", t.ndim)

Rank of t :  1


In [18]:
print("Shape of t : ", t.shape)

Shape of t :  (7,)


In [22]:
print("t[0] t[1] t[-1] = ", t[0], t[1], t[-1])
# Element

t[0] t[1] t[-1] =  0.0 1.0 6.0


In [20]:
print("t[2:5] t[4:-1] = ", t[2:5], t[4:-1])
# Slicing

t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]


In [21]:
print("t[:2] t[3:] = ", t[:2], t[3:])
# Slicing

t[:2] t[3:] =  [0. 1.] [3. 4. 5. 6.]


### 2D Array with Numpy

In [23]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])

In [24]:
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [25]:
print("Rank of t : ", t.ndim)

Rank of t :  2


In [26]:
print("Shape of t : ", t.shape)

Shape of t :  (4, 3)


### PyTorch Tensor

In [27]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])

In [28]:
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [30]:
print(t.dim()) #rank

1


In [31]:
print(t.shape) 

torch.Size([7])


In [32]:
print(t.size()) # shape

torch.Size([7])


In [33]:
print(t[0], t[1], t[-1]) # Element

tensor(0.) tensor(1.) tensor(6.)


In [34]:
print(t[2:5], t[4:-1])

tensor([2., 3., 4.]) tensor([4., 5.])


In [35]:
print(t[:2], t[3:])

tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [36]:
t = torch.FloatTensor([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])

In [37]:
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [38]:
print(t.dim())

2


In [39]:
print(t.size())

torch.Size([4, 3])


In [41]:
print(t[:, 1])

tensor([ 2.,  5.,  8., 11.])


In [43]:
print(t[:, 1].size())

torch.Size([4])


In [44]:
print(t[:, -1])

tensor([ 3.,  6.,  9., 12.])
