there are 5 general mechanisms for creating arrays.

 1. Conversion from other Python structures(e.g.,lists,tuples)
 2. Intrinsic numpy array creation objects(e.g., arrange ones, zeros,etc.)
 3. Reading arrays from disk, either from standard or custom format
 4. Creating arrays from raw bytes through the use of strings or buffers
 5. Use of special library functions(e.g., random)
 
 ### Arrays

In [3]:
import numpy as np

In [ ]:
x = np.array([2,3,1,0])

In [5]:
x

array([2, 3, 1, 0])

In [6]:
x = np.array([2, 3, 1, 0])

In [7]:
x

array([2, 3, 1, 0])

In [8]:
x = np.array([[1,2,0],[0.+0.j],[1.+1.j, 3.+0.j]])

In [9]:
x

array([list([1, 2, 0]), list([0j]), list([(1+1j), (3+0j)])], dtype=object)

In [10]:
x = np.array([[ 1.+0.j, 2.+0.j], [ 0.+0.j, 0.+0.j], [ 1.+1.j, 3.+0.j]])

In [11]:
x

array([[1.+0.j, 2.+0.j],
       [0.+0.j, 0.+0.j],
       [1.+1.j, 3.+0.j]])

### Intricsic Numpy Array Creation

Numpy has bulit-in functions for creating arrays from scratch:

zeros(shape) will create an array filled with 0 values with the specified shape. the default dtype is float64

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(2,10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [15]:
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [16]:
np.arange(2,3,0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

note that there are some subtieties regarding the las usage that the user should be aware of that are described in the arange docstring

linspace() will create arrays with a specified number of elements, and spaced equally between the specified beginninh and end values.

In [17]:
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

indices() will create a set of arrays(stacked as a one-higher dimensioned array). one perdimension with each representing variation in that dimension.

In [18]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

### Reading Arrays From Disk

This is presumably the most common case of large array creation.the dstails, of course, depend greatly on the format of data on disk and so this section can only give general pointers on how to handle various formats.

#### Standard Binary Formats
Various fields have standard formats for array data. the following list the ones with known python libraries to read them and return numpy arrays(there may be others for which it is possible to read and convert to numpy arrays so check the last section as well)

> HDF5: h5py

> FITS: Astropy

examples of formats that can't be read directly but for which it is not hard to convert are those formats supported by libraries like PIL(able ro read and write many image formats such as jpg, png, etc).

#### Common ASCII Formats
comma Separated Value file(CSV) are widely used (and an export and import option for programs like Excel). there are a number of ways of reading these files in Python.
there are CSV functions in Python and functions in pylab (part of matplotlib)

More generic ascii files can be read using the io package in scipy

#### Custom Binary Formats
There are a variety of approaches one can use. If the file has a relatively simple format then one can write a simple I/O library and use the numpy fromfile() funcion and /rofile() method to read and write numpy arrays directly(mind your byteorder though!) if a good C or C++ library exists that read the data. one can wrap that library with a  variety of techniques though that certainly is muxh more work and requires significantly moew advanced knowledge to interface with C or C++

#### Use of Special 
There are libraries that can be used to generate arrays for special purposes and it isn't possible to enumerate all of them. The most common uses are use of the many array generation function in random that can generate arrays of random values, and some utility functions to generate special matrices(e.g. diagonal)