Array indexing refers to any use of the square brackets ([]) to index array values. There are many options to indexing, which give numpy indexing great power, but with power comes some complexity and the potential for confusion. This section is just an overview of the various options and issues related to indexing.Aside from single element indexing, the details on most of these options are to be found in related sections.

### Assignment vs referencing
Most of the following examples show the use of indexing when referencing data in an array. The examples work just as well when assigning to an array.See the section at the end for specific examples and explanations on how assignments work.

### Single element indexing
Single element indexing for a 1-D array is what one expects. It work exactly like that for other standard Python sequences.It is O-based, and accepts negative indeices for indexing from the end of the array.

In [1]:
import numpy as np

In [2]:
x = np.arange(10)

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
x[-2]

8

Unlike lists and tuples, numpy arrays support multidimensional indexing for multidimensional arrays. that means that it is not necessary to separate each dimension's index into its own set of square brackets

In [5]:
x.shape = (2,5)

In [6]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
x[1,3]

8

In [8]:
x[1,-1]

9

note that if one indexes a multidimensional array with fewer indices than dimensions, one gets a subdimensional array. For example:

In [9]:
x[0]

array([0, 1, 2, 3, 4])

In [10]:
x[0][2]

2

In [11]:
x = np.arange(10)

In [12]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x[2:5]

array([2, 3, 4])

In [14]:
x[:-7]

array([0, 1, 2])

In [15]:
x[1:7:2]

array([1, 3, 5])

In [16]:
y = np.arange(35).reshape(5,7)

In [17]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [18]:
y[1:5:2,::3]

array([[ 7, 10, 13],
       [21, 24, 27]])

Note that slices