Array indexing refers to any use of the square brackets ([]) to index array values. There are many options to indexing, which give numpy indexing great power, but with power comes some complexity and the potential for confusion. This section is just an overview of the various options and issues related to indexing.Aside from single element indexing, the details on most of these options are to be found in related sections.

### Assignment vs referencing
Most of the following examples show the use of indexing when referencing data in an array. The examples work just as well when assigning to an array.See the section at the end for specific examples and explanations on how assignments work.

### Single element indexing
Single element indexing for a 1-D array is what one expects. It work exactly like that for other standard Python sequences.It is O-based, and accepts negative indeices for indexing from the end of the array.

In [1]:
import numpy as np

In [2]:
x = np.arange(10)

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
x[-2]

8

Unlike lists and tuples, numpy arrays support multidimensional indexing for multidimensional arrays. that means that it is not necessary to separate each dimension's index into its own set of square brackets

In [5]:
x.shape = (2,5)

In [6]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
x[1,3]

8

In [8]:
x[1,-1]

9

note that if one indexes a multidimensional array with fewer indices than dimensions, one gets a subdimensional array. For example:

In [9]:
x[0]

array([0, 1, 2, 3, 4])

In [10]:
x[0][2]

2

In [11]:
x = np.arange(10)

In [12]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x[2:5]

array([2, 3, 4])

In [14]:
x[:-7]

array([0, 1, 2])

In [15]:
x[1:7:2]

array([1, 3, 5])

In [4]:
y = np.arange(35).reshape(5,7)

In [17]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [18]:
y[1:5:2,::3]

array([[ 7, 10, 13],
       [21, 24, 27]])

Note that slices pf arrays do not copy the internal array data but only produce new views of the original data.

It is possible to index arrays with other arrays for the purposes of selecting lists of values out of arrays into new arrays. There are two different ways of accomplishing this.One uses one or more arrays of index values. The other involves giving a boolean array of the proper shape to indicate the values to be selected. Index arrays are a very powerful tool that allow one to avoid looping over individual elements in arrays and thus greatly improve performance.

It is possible to use special features to effectively increase the number of dimensions in an array through indexing so the resulting array aquires the shape needed for use in an expression or with a specific function.

### Index arrays
Numpy arrays may be indexed with other arrays (or any other sequece- like object that can be converted to an array. such as lists, with the exception of tuples;
see the end of this document for why this is). The use of index arrays ranges from simple. straightforward cases to complex, hard-to-understand cases, For all cases of index arrays.what is returned is a copy of the original data, not a view as one gets for slices.

index arrays must be of integer type. Each value in the array indicates which value in the array to use in place of the index.To illustrate:

In [2]:
x = np.arange(10,1,-1)

In [3]:
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [4]:
x[np.array([3, 3, 1, 8])]

array([7, 7, 9, 2])

In [5]:
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

The index array consisting of the values 3, 3, 1 and 8 correspondingly create an array of length 4(same as the index array) where each index is replaced by the value the index array has in the array being indexed.

Negative values are permitted and work as they do with single indices or slices:

In [6]:
x[np.array([3,3,-3,8])]

array([7, 7, 4, 2])

it is an error to have index values out of bounds

In [7]:
x[np.array([3, 3, 20, 8])]

IndexError: index 20 is out of bounds for axis 0 with size 9

Generally speaking, what is returned when index arrays are used is an array with the same shape as the index array. but with the type and values of the array being indexed. As an example, we can use a multidimensional index array instead

In [8]:
x[np.array([[1,1],[2,3]])]

array([[9, 9],
       [8, 7]])

### Indexinf Multi-dimensional arrays
Things become more complex when multidimensional arrays are indexed, particularly with multidimensional index arrays. These tend to be more unusual uses, but they are permitted, and they are useful for some problems. We'll start with simplest multidimensional case(using the array y from the previous examples):

In [4]:
y[np.array([0,2,4]), np.array([0,1,2])]

array([ 0, 15, 30])

In [5]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

-> 0행의 0열 2행 1열 4행 2열

In [6]:
y[np.array([0,2,4]),np.array([0,1])]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

If the index arrays do not have the same shape, there is an attempt to broadcast them to the same shape. If they cannot be broadcast to the same shape, an exception is raised

In [7]:
y[np.array([0,2,4]), 1]

array([ 1, 15, 29])

In [8]:
y[np.array([0,2,4])]

array([[ 0,  1,  2,  3,  4,  5,  6],
       [14, 15, 16, 17, 18, 19, 20],
       [28, 29, 30, 31, 32, 33, 34]])

### Boolean or "mask" index arrays
Boolean arrays used as indices are treated in a different manner entirely than index arrays. Boolean arrays must be of the same shape as the initial dimensions of the array being indexed. In the most straightforward case, the boolean array has the same shape

In [6]:
b = y>20

In [7]:
b

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [8]:
b[b]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [9]:
y[b]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

Unlike in the case of integer index arrays, in the boolean case,the result is a 1-D array containing all the elements in the indexed array corresponding to all the true elements in the boolean array.The elements in the indexed array are always iterated and returned in row-major (C-style) order.The result is also identical to ```y[np.nonzero(b)]``` As with index arrays. what is returned is a copy of the data. not a view as one gets with slices.

In [10]:
b[:,5]

array([False, False, False,  True,  True])

In [12]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [11]:
y[b[:,5]]

array([[21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

Here the 4th and 5th rows are selected from the indexed array and combined to make a 2-D array


In [2]:
x = np.arange(30).reshape(2,3,5)

In [3]:
x

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [14]:
b = np.array([[True, True, False], [False, True, True]])

In [15]:
x[b]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

### Combining index arrays with slices
Index arrays may be combined with slices.

In [18]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [17]:
y[np.array([0,2,4]),1:3]

array([[ 1,  2],
       [15, 16],
       [29, 30]])

In [19]:
b = y > 20

In [21]:
b

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [22]:
y[b[:,5],1:3]

array([[22, 23],
       [29, 30]])

### Structural indexing tools
To facilitate easy matching of array shapes with expressions and in assignments, the np.newaxis object can be used within array indices to add new dimensions with a size of 1. For example

In [23]:
y.shape

(5, 7)

In [28]:
y[:,np.newaxis,:].shape

(5, 1, 7)

In [29]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

note that there are no new elements in the array, just that the dimensionality is increased.This can be handy to combine two arrays in a way that otherwise would require explicitly reshaping operations.

In [25]:
x = np.arange(5)

In [26]:
x

array([0, 1, 2, 3, 4])

In [27]:
x[:,np.newaxis] + x[np.newaxis,:]

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [30]:
z = np.arange(81).reshape(3,3,3,3)

In [31]:
z

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59],
         [60, 61, 62]],

        [[63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80]]]])

In [32]:
z[1,...,2]

array([[29, 32, 35],
       [38, 41, 44],
       [47, 50, 53]])

This is equivalent to

In [33]:
z[1,:,:,2]

array([[29, 32, 35],
       [38, 41, 44],
       [47, 50, 53]])

### Assignong values to indexed arrays


In [34]:
x = np.arange(10)

In [35]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
x[2:7] = 1

In [37]:
x

array([0, 1, 1, 1, 1, 1, 1, 7, 8, 9])

In [38]:
x[2:7] = np.arange(5)

In [39]:
x

array([0, 1, 0, 1, 2, 3, 4, 7, 8, 9])

In [41]:
x[1] = 1.2

In [42]:
x[1]

1

In [43]:
x[1] = 1.2j

TypeError: can't convert complex to int

Note that assignments may result in changes if assigning higher types to lower types(like floats to ints) or even exceptions(assigning complex to floats or ints)

In [44]:
x = np.arange(0, 50, 10)

In [45]:
x

array([ 0, 10, 20, 30, 40])

In [46]:
x[np.array([1,1,3,1])] += 1

In [47]:
x

array([ 0, 11, 20, 31, 40])

Unlike some of the references (such as array and mask indices) assignments are always made to the original data in the array (indeed, nothing else would make sense!). Note though, that some actions may not work as one may naively expect. This particular example is often surprising to people

### Dealing with variable numbers of indices within programs

In [48]:
indices = (1,1,1,1)

In [50]:
z[indices]

40

In [51]:
z

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59],
         [60, 61, 62]],

        [[63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80]]]])

In [52]:
indices = (1,1,1,slice(0,2))

In [53]:
indices

(1, 1, 1, slice(0, 2, None))

In [54]:
z[indices]

array([39, 40])

In [55]:
indices = (1, Ellipsis, 1)

In [56]:
z[indices]

array([[28, 31, 34],
       [37, 40, 43],
       [46, 49, 52]])

In [57]:
z[[1,1,1,1]]

array([[[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]]])

In [58]:
z[(1,1,1,1)]

40

For this reason it is possible to use the output from the np.nonzero() function directly as an index since it always returns a tuple of index arrays.

Because  the special treatment of tuples, they are not automatically converted to an array as a list would be.