In [1]:
import time

In [2]:
time.time()

1563863628.3984983

python의 date package는 기본 설계부터 잘못되어서 third party librarly를 사용한다.



In [3]:
import datetime

In [4]:
dir(datetime)

['MAXYEAR',
 'MINYEAR',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'date',
 'datetime',
 'datetime_CAPI',
 'sys',
 'time',
 'timedelta',
 'timezone',
 'tzinfo']

'timedelta' : 시각

'timezone' : 다양한 시간

'date' : 날짜

'time' : 시간

'datetime' : ??? 설계 잘몬함

In [6]:
datetime.datetime

datetime.datetime

In [23]:
from datetime import datetime, timedelta, date, time
# 관례상 이렇게 사용한다.

In [8]:
a = datetime(2019,7,22)

In [9]:
a

datetime.datetime(2019, 7, 22, 0, 0)

In [10]:
dir(a)

['__add__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__radd__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rsub__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 'astimezone',
 'combine',
 'ctime',
 'date',
 'day',
 'dst',
 'fold',
 'fromisoformat',
 'fromordinal',
 'fromtimestamp',
 'hour',
 'isocalendar',
 'isoformat',
 'isoweekday',
 'max',
 'microsecond',
 'min',
 'minute',
 'month',
 'now',
 'replace',
 'resolution',
 'second',
 'strftime',
 'strptime',
 'time',
 'timestamp',
 'timetuple',
 'timetz',
 'today',
 'toordinal',
 'tzinfo',
 'tzname',
 'utcfromtimestamp',
 'utcnow',
 'utcoffset',
 'utctimetuple',
 'weekday',
 'year']

In [11]:
a.year

2019

In [12]:
a.month

7

In [14]:
a.ctime()

'Mon Jul 22 00:00:00 2019'

In [18]:
b = timedelta(99)

In [19]:
a + b

datetime.datetime(2019, 10, 29, 0, 0)

In [28]:
a = datetime.strptime('2019-07-23','%Y-%m-%d')

In [29]:
a

datetime.datetime(2019, 7, 23, 0, 0)

python 은 고유의 타입캐스팅이 없다.

numpy는 C기반으로 타입캐스팅하는 기능을 지워난다.

In [30]:
import numpy as np

In [45]:
np.lookfor('casting')

Search results for 'casting'
----------------------------
numpy.abs
    Calculate the absolute value element-wise.
numpy.add
    Add arguments element-wise.
numpy.cos
    Cosine element-wise.
numpy.exp
    Calculate the exponential of all elements in the input array.
numpy.gcd
    Returns the greatest common divisor of ``|x1|`` and ``|x2|``
numpy.lcm
    Returns the lowest common multiple of ``|x1|`` and ``|x2|``
numpy.log
    Natural logarithm, element-wise.
numpy.mod
    Return element-wise remainder of division.
numpy.sin
    Trigonometric sine, element-wise.
numpy.tan
    Compute tangent element-wise.
numpy._arg
    DO NOT USE, ONLY FOR TESTING
numpy.cbrt
    Return the cube-root of an array, element-wise.
numpy.ceil
    Return the ceiling of the input, element-wise.
numpy.conj
    Return the complex conjugate, element-wise.
numpy.cosh
    Hyperbolic cosine, element-wise.
numpy.exp2
    Calculate `2**p` for all `p` in the input array.
numpy.fabs
    Compute the absolute values elem

In [34]:
a = np.array([1,2,3])

In [35]:
a

array([1, 2, 3])

In [36]:
a.dtype

dtype('int32')

In [38]:
a.dtype = 'int8'

In [39]:
a

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0], dtype=int8)

값이 바껴버린다.

In [40]:
a = np.array([1,2,3])

In [41]:
a

array([1, 2, 3])

In [43]:
a.astype('float64')

array([1., 2., 3.])

type 바꿀때 astype을 사용하면된다. (번외 viewtype)