shape 변환.

Broad Cast의 한계를 극복하는 방법.

설명 보는 방법

 - np.info()
 - np.lookfor()


In [1]:
import numpy as np

In [3]:
np.lookfor??

In [5]:
np.lookfor('shape')

Search results for 'shape'
--------------------------
numpy.shape
    Return the shape of an array.
numpy.reshape
    Gives a new shape to an array without changing its data.
numpy.flip
    Reverse the order of elements in an array along the given axis.
numpy.full
    Return a new array of given shape and type, filled with `fill_value`.
numpy.isin
    Calculates `element in test_elements`, broadcasting over `element` only.
numpy.ones
    Return a new array of given shape and type, filled with ones.
numpy.empty
    Return a new array of given shape and type, without initializing entries.
numpy.zeros
    Return a new array of given shape and type, filled with zeros.
numpy.resize
    Return a new array with the specified shape.
numpy.ndarray
    ndarray(shape, dtype=float, buffer=None, offset=0,
numpy.ndindex
    An N-dimensional iterator object to index arrays.
numpy.squeeze
    Remove single-dimensional entries from the shape of an array.
numpy.ma.shape
    Return the shape of an array.

In [6]:
np.lookfor('create array')

Search results for 'create array'
---------------------------------
numpy.array
    Create an array.
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or POINTER.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.ctypeslib.as_ctypes
    Create and return a ctypes object from a numpy array.  Actually
numpy.asarray
    Convert the input to an array.
numpy.ndarray
    ndarray(shape, dtype=float, buffer=None, offset=0,
numpy.recarray
    Construct an ndarray that allows field access using attributes.
numpy.chararray
    chararray(shape, itemsize=1, unicode=Fa

In [7]:
np.lookfor('* array')

Search results for '* array'
----------------------------
numpy.exp
    Calculate the exponential of all elements in the input array.
numpy.cbrt
    Return the cube-root of an array, element-wise.
numpy.exp2
    Calculate `2**p` for all `p` in the input array.
numpy.fmax
    Element-wise maximum of array elements.
numpy.fmin
    Element-wise minimum of array elements.
numpy.modf
    Return the fractional and integral parts of an array, element-wise.
numpy.rint
    Round elements of the array to the nearest integer.
numpy.sqrt
    Return the non-negative square-root of an array, element-wise.
numpy.expm1
    Calculate ``exp(x) - 1`` for all elements in the array.
numpy.isnan
    Test element-wise for NaN and return result as a boolean array.
numpy.isnat
    Test element-wise for NaT (not a time) and return result as a boolean array.
numpy.log10
    Return the base 10 logarithm of the input array, element-wise.
numpy.log1p
    Return the natural logarithm of one plus the input array, ele

In [8]:
a = np.array([100])

In [9]:
a

array([100])

In [10]:
a = np.array(100)

In [12]:
a
# scalar

array(100)

In [13]:
a = np.array([[1, 2, 3],[4,5,6]])

In [14]:
a

array([[1, 2, 3],
       [4, 5, 6]])

axis = 0 : row

axis = 1 : column

stride가 보폭이 작다. 

-> 컬럼을 줄이는 reduce도 빠르다.

In [15]:
a = np.arange(27)

In [16]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

## * reshape

stride를 이용하기 때문에 real time으로 실행되기 때문에 비용이 안든다. 



In [17]:
a.shape

(27,)

In [19]:
a.reshape(4,6)

ValueError: cannot reshape array of size 27 into shape (4,6)

In [20]:
a.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

reshape에서 주의해야 할 점 

mutable function이 아니라서 자기 자신이 바뀌지 않는다.

In [21]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

연속된 공간에 데이터를 저장하고 stride개념을 사용하기 때문에 굳이 변환하지 않는다.

In [22]:
b = a.reshape(3,9)

In [23]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [24]:
b[0][0] = 100

In [25]:
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26])

-> reshape는 참조를 같이해서 copy를 사용해야 한다,

In [26]:
b = a.reshape(3,9).copy()

In [27]:
b

array([[100,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26]])

In [30]:
b = a.reshape(3, -1)
# -1 : automation

In [29]:
b

array([[100,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26]])

In [31]:
b = a.reshape(-1, 9)

In [32]:
b

array([[100,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26]])

In [33]:
b = a.reshape(-1, -1)

ValueError: can only specify one unknown dimension

In [34]:
b = a.reshape(3, -2)

In [35]:
b

array([[100,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26]])

-2,.., -100

'-'쓰면 자동적으로 automation을 지원한다.

관례상 -1만 쓰자.

---

## resize

In [37]:
a.resize((3,9))

In [38]:
a

array([[100,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26]])

resize -> 자기자신을 변경 후 반환한다.

mutable function이다.

잘안쓴다. 자기자신을 바꾸는 기능은 위험한 기능.

In [41]:
a = np.arange(27)

In [ ]:
a.resize((3,5))

In [43]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [40]:
a.resize((-1,10))

ValueError: negative dimensions not allowed

---

## split

3가지. 

In [46]:
a = np.arange(27)

In [47]:
a = a.reshape(3,9)

In [48]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [49]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

numpy 접근방식 function 방식 메소드 방식

In [52]:
'split' in dir(a)

False

In [53]:
np.split(a,(1,2))

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

split : 0-1, 1-2, 2-끝

In [54]:
np.split(a,(2,2))

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([], shape=(0, 9), dtype=int32),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

split : 0-2, 2-끝

In [55]:
np.split(a,(2,5))

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]]),
 array([], shape=(0, 9), dtype=int32)]

In [56]:
np.split(a,(-2,5))

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26]]),
 array([], shape=(0, 9), dtype=int32)]

In [57]:
np.split(a, (5, 5), axis =1)

[array([[ 0,  1,  2,  3,  4],
        [ 9, 10, 11, 12, 13],
        [18, 19, 20, 21, 22]]),
 array([], shape=(3, 0), dtype=int32),
 array([[ 5,  6,  7,  8],
        [14, 15, 16, 17],
        [23, 24, 25, 26]])]

In [58]:
np.hsplit??

In [59]:
np.hsplit(a, (5,))

[array([[ 0,  1,  2,  3,  4],
        [ 9, 10, 11, 12, 13],
        [18, 19, 20, 21, 22]]), array([[ 5,  6,  7,  8],
        [14, 15, 16, 17],
        [23, 24, 25, 26]])]

In [60]:
np.vsplit(a, (2,))

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

## stack

numpy 배열 합치기

In [61]:
np.stack??

In [62]:
b = np.arange(5)

In [63]:
c = np.arange(5)

In [64]:
np.stack((b,c),1)

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [65]:
b

array([0, 1, 2, 3, 4])

In [66]:
c

array([0, 1, 2, 3, 4])

In [67]:
np.hstack((b,c))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [68]:
np.vstack((b,c))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [69]:
np.r_??

'r_' 단축 표현 matlab 에서 왔다.

In [70]:
np.r_[b,c]

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [71]:
np.c_[b,c]

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [72]:
np.s_[b,c]

(array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]))

단축표현 _3총사 

r_, c_, s_

In [73]:
[1,2,3,4,5][slice(1,5)]

[2, 3, 4, 5]

In [74]:
[1,2,3,4,5][1:5]

[2, 3, 4, 5]

-> s_가 저거 만들어준다. 저거 : 

In [75]:
np.s_[1,3]

(1, 3)

In [76]:
np.arange(10)[np.s_[1]]

1

In [77]:
np.column_stack??

In [78]:
np.column_stack([b,c])

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

slicing 기법과 stack 기법을 잘 익혀두자.

---

골치아푼 reshape

In [80]:
a = np.arange(6)

In [81]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [82]:
a

array([0, 1, 2, 3, 4, 5])

a를 2차원으로 만들고 싶옹

[[0,1,2,3,4,5]]

In [88]:
a[None]

array([[0, 1, 2, 3, 4, 5]])

In [86]:
np.newaxis is None

True

In [87]:
a[np.newaxis]

array([[0, 1, 2, 3, 4, 5]])

새롭게 축만든기

In [89]:
a = a.reshape(2,3)

In [90]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [91]:
a[np.newaxis]
# 전체 차원 증가

array([[[0, 1, 2],
        [3, 4, 5]]])

In [92]:
a[:,np.newaxis]
# 1카피 안쪽 원소 차원 증가

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [93]:
a[:,:,np.newaxis]
## 2카피 안쪽 원소 차원 증가

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [94]:
a = np.arange(6)

In [96]:
a

array([0, 1, 2, 3, 4, 5])

In [97]:
a[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [100]:
np.expand_dims??

In [99]:
np.expand_dims(a,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [101]:
np.expand_dims(a,2)

C:\Users\scminnoG15\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Both axis > a.ndim and axis < -a.ndim - 1 are deprecated and will raise an AxisError in the future.
  """Entry point for launching an IPython kernel.


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

np.expand_dims 은 차원을 1카피씩만 증가시켜줄 수 있다.

In [102]:
np.expand_dims(a,200)

C:\Users\scminnoG15\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Both axis > a.ndim and axis < -a.ndim - 1 are deprecated and will raise an AxisError in the future.
  """Entry point for launching an IPython kernel.


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [103]:
a = np.arange(27).reshape(3, 3, 3)

In [104]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [110]:
np.swapaxes??

In [106]:
np.swapaxes(a, 0, 2)

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [111]:
np.moveaxis??

In [108]:
np.moveaxis(a, 0, 2)

array([[[ 0,  9, 18],
        [ 1, 10, 19],
        [ 2, 11, 20]],

       [[ 3, 12, 21],
        [ 4, 13, 22],
        [ 5, 14, 23]],

       [[ 6, 15, 24],
        [ 7, 16, 25],
        [ 8, 17, 26]]])

정리

1. 생성

2. 

3. 

4. indexslicing

5. shape